### ISSUE TITLE
[Bug] Doesn't work with hires fix

### ISSUE THREAD

**Issue by Picometer12** [acorderob/sd-webui-sendtonegative#3]
## Description

Add compatibility for the hires.fix upscaling feature of Automatic1111.

## Additional context

This might be more appropriately listed as a bug, but I'm not 100% sure that I'm not missing a setting somewhere or possibly having some kind of interference with a different extension. This extension works perfectly if I have hires fix turned off, but when hires fix is turned on, the tokens that are supposed to be sent to the negative prompt are correctly applied to the negative prompt for the before-upscale image, but then incorrectly applied to the positive prompt during the post-upscale steps. 

Repro steps: generate with a prompt such as `man, hat, grayscale, <!((woman, long hair, colorful))!>` with hi.res enabled vs disabled.

Also, thanks for making this! Awesome stuff. I've been hoping that someone would make a "send to negative" feature ever since the first wildcard extension came out.

**Comment by acorderob** [comment]
I can't reproduce it. I tested your example with hires fix and It works fine for me. Give me an example with all the settings to test, but i think it might be some other extension interfering.

**Comment by Picometer12** [comment]
Apologies, that wasn't actually a very good example (at least with default settings on SD 1.5). 

Here's a better example -- I don't know if git does anything to the metadata so here's how it appears in PNG Info tab: 



```parameters

man, portrait
Negative prompt: glasses
Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 524507735, Size: 512x512, Model hash: e1441589a6, Model: v1-5-pruned, VAE hash: c6a580b13a, VAE: vae-ft-mse-840000-ema-pruned.ckpt, Denoising strength: 0.7, Hires upscale: 2, Hires upscaler: None, Version: v1.6.0```

My prompt was Positive: man, portrait <!glasses!> 

When I turn off all extensions except sendtonegative or drop a fresh copy of automatic1111 in a separate folder and install only sendtonegative, I get no glasses if I don't use hires fix and I do get glasses when I use hires.fix

![53578-2023-10-13](https://github.com/acorderob/sd-webui-sendtonegative/assets/122178441/056ab491-f798-45a6-8cfa-aeeeb5a611fa)

**Comment by acorderob** [comment]
I tested with your example and indeed the final image gets glasses.

But this is not caused by the extension, because the metadata is correct ("glasses" end up only in the negative prompt in the upscaled image) and i confirmed that the hires fix phase does not processes again the prompt (the prompt and negative prompt is the same as in the initial phase).

So this is just the result of the settings and possibly the model.

**Comment by acorderob** [comment]
Apparently A1111 uses different variables for hires fix prompts. Should be fixed now.
