### ISSUE TITLE
[Request] Make available in ComfyUI

### ISSUE THREAD

**Issue by Alyndiar** [acorderob/sd-webui-sendtonegative#5]
## Description

Create a node in ComfyUI to apply send to negative on a positive and negative prompt pair

## Additional context

There is currently no node in ComfyUI to support this functionality. This is sorely missing for those of us who like to use Dynamic Prompts

**Comment by acorderob** [comment]
This an A1111 extension. I'm not interested in ComfyUI.

**Comment by Alyndiar** [comment]
That is quite alright. Can I have your permission to create a ComfyUI node
based on it?

**Comment by acorderob** [comment]
Of course. This is open source after all.
